### ISSUE TITLE
improvment idea

### ISSUE THREAD

**Issue by hyperbaba** [sametsazak/sysmon#3]
This project have a great idea,
i have an suggestion to create a script that automatically generates wazuh config based on sigma rules git repo. Something like AtomicThreatCoverage that includes EndPoint Detection using wazuh

**Comment by sametsazak** [comment]
Thank you for suggestion,

I think your idea is very nice. 

This repo is quite old but i will improve your idea.

**Comment by sametsazak** [comment]
@hyperbaba https://github.com/SanWieb/sigWah
